#! /bin/sh

#PYWAL
. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d 1 2 3 4 5
bspc monitor -d      

bspc config normal_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc rule -a "TL 155.3 [AUR]" state=floating
bspc rule -a TL state=floating
bspc rule -a Minecraft state=floating
bspc rule -a MEGAsync state=floating border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config pointer_motion_interval 5

# autostart
setxkbmap us &
picom -fb --backend glx --config ~/.config/picom.conf &
lxsession &
xsetroot -cursor_name left_ptr
killall -KILL greenclip; greenclip daemon &
kdeconnect-indicator &
wal -R
~/.local/bin/launchbar.sh
