#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d 1 2 3 4 5

bspc config normal_border_color "#4C566A"
bspc config focused_border_color "#5E81AC"
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a MEGAsync state=floating border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# autostart
systemctl --user disable pipewire --now
systemctl --user disable pipewire.socket --now
systemctl --user disable wireplumber --now

~/.config/polybar/launch.sh
setxkbmap us &
picom -fb --backend glx --config ~/.config/picom.conf&
nitrogen --restore &
lxsession &
xsetroot -cursor_name left_ptr
greenclip daemon &
