#! /bin/sh

#PYWAL
. "${HOME}/.cache/wal/colors.sh"


#bspc monitor -d 1 2 3 4 5
bspc monitor -d      

bspc config normal_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

bspc rule -a "Blueman-manager" state=floating
bspc rule -a "ru-turikhay-tlauncher-bootstrap-Bootstrap" state=floating
bspc rule -a "Yad" state=floating
bspc rule -a MEGAsync state=floating border=off
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config pointer_motion_interval 1

# autostart
picom -fb --backend glx --config ~/.config/picom.conf &
setxkbmap us &
xsetroot -cursor_name left_ptr &
wal -R 
pgrep -u $(whoami) -x sxhkd > /dev/null || sxhkd &
pgrep -u $(whoami) -f "dunst" || dunst &
pgrep -u $(whoami) -f "lxsession" || lxsession &
pgrep -u $(whoami) -f "greenclip" || greenclip daemon &
pgrep -u $(whoami) -f "polybar" || ~/.local/bin/launchbar.sh

# unblock distracting sites
#$HOME/.local/bin/block.sh
